server:
  port: 4650

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: Api-Gateway
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: post
            redirect-uri: http://localhost:4650/login/oauth2/code/google
            scope:
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/mail/**
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/event/**
