server:
  port: 4650

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/mail/**
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
