server:
  port: 4650

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: Api-Gateway
  security:
    oauth2:
      client:
        registration:
          quotes-client:
            redirect-uri: http://localhost:4650/login/oauth2/code/quotes-client
            provider: keycloak
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile
              - roles
        provider:
          keycloak:
            issuer-uri: http://localhost:9001/auth/realms/event
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/mail/**
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/event/**
